{{- if .Values.enabled }}
{{ $labels := include "networkpolicy.labels" . }}
{{- range .Values.policies }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  labels:
    {{- $labels | nindent 4 }}
  name: {{ .name }}
spec: 
{{ toYaml .spec | indent 2 }}
{{ end }}
{{ end }}
